Repository mollie/mollie-api-node, pull requests merged in 2024-09, with the labels that each got.

#370 Payments: add missing include type
  src/createMollieClient.ts
  src/data/payments/data.ts
Labels: API discrepancy

#373 Payments, Orders: add dashboard urls
  src/data/orders/OrderHelper.ts
  src/data/orders/data.ts
  src/data/payments/PaymentHelper.ts
  src/data/payments/data.ts
  tests/unit/resources/orders.test.ts
  tests/unit/resources/payments.test.ts
Labels: API discrepancy

#374 Methods: fix types for pricing and issuer
  src/data/methods/data.ts
Labels: API discrepancy

#359 Update changelog for v4.0.0
  CHANGELOG.md
  MIGRATION.md
  README.md
Labels: maintenance

#376 Update payment methods
  CHANGELOG.md
  MIGRATION.md
  README.md
  src/data/global.ts
Labels: API discrepancy

#377 Change path of the types in package.json
  package.json
Labels: bug

#380 Fix Documentation for async iterators in README
  README.md
Labels: maintenance

#369 Add `MaybeArray` utility type
  src/Options.ts
  src/binders/customers/payments/parameters.ts
  src/binders/methods/parameters.ts
  src/binders/orders/parameters.ts
  src/binders/payments/orders/parameters.ts
  src/binders/payments/parameters.ts
  src/communication/NetworkClient.ts
  src/communication/buildUrl.ts
  src/types/MaybeArray.ts
Labels: refactor

#368 Replace `checkId` with `assertWellFormedId`
  src/binders/customers/CustomersBinder.ts
  src/binders/customers/mandates/CustomerMandatesBinder.ts
  src/binders/customers/payments/CustomerPaymentsBinder.ts
  src/binders/customers/subscriptions/CustomerSubscriptionsBinder.ts
  src/binders/orders/OrdersBinder.ts
  src/binders/orders/orderlines/OrderLinesBinder.ts
  src/binders/orders/shipments/OrderShipmentsBinder.ts
  src/binders/organizations/OrganizationsBinder.ts
  src/binders/paymentLinks/PaymentLinksBinder.ts
  src/binders/payments/PaymentsBinder.ts
  src/binders/payments/captures/PaymentCapturesBinder.ts
  src/binders/payments/chargebacks/PaymentChargebacksBinder.ts
  src/binders/payments/orders/OrderPaymentsBinder.ts
  src/binders/payments/refunds/PaymentRefundsBinder.ts
  src/binders/profiles/ProfilesBinder.ts
  src/binders/profiles/giftcardIssuers/ProfileGiftcardIssuersBinder.ts
  src/binders/profiles/methods/ProfileMethodsBinder.ts
  src/binders/profiles/voucherIssuers/ProfileVoucherIssuersBinder.ts
  src/binders/refunds/orders/OrderRefundsBinder.ts
  src/binders/subscriptions/payments/SubscriptionPaymentsBinder.ts
  src/plumbing/assertWellFormedId.ts
  src/plumbing/checkId.ts
Labels: refactor

#371 Add captures API endpoints
  src/binders/payments/captures/PaymentCapturesBinder.ts
  src/binders/payments/captures/parameters.ts
  src/binders/payments/parameters.ts
  src/createMollieClient.ts
  src/data/payments/captures/CaptureHelper.ts
  src/data/payments/captures/data.ts
  src/data/payments/data.ts
  src/data/settlements/data.ts
  tests/integration/payments.test.ts
  tests/unit/resources/payments/captures.test.ts
Labels: API extension
